config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("taichi_dfw.users.urls")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("styles/", include("taichi_dfw.styles.urls")),
    path("resources/", include("taichi_dfw.resources.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

taichi_dfw/resources/urls.py
from django.urls import path

from .views import resource_detail_view, resource_list_view

app_name = "resources"
urlpatterns = [
    path("<slug:slug>/", view=resource_detail_view, name="detail"),
    path("", view=resource_list_view, name="list"),
]

taichi_dfw/styles/urls.py
from django.urls import path

from .views import (
    meeting_detail_view,
    series_detail_view,
    style_detail_view,
    style_list_view,
)

app_name = "styles"
urlpatterns = [
    path("series/<slug:slug>/", view=series_detail_view, name="series-detail"),
    path("meeting/<int:pk>/", view=meeting_detail_view, name="meeting-detail"),
    path("<slug:slug>/", view=style_detail_view, name="detail"),
    path("", view=style_list_view, name="list"),
]

taichi_dfw/users/urls.py
from django.urls import path

from taichi_dfw.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

taichi_dfw/locations/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django_google_maps import fields as map_fields
from django_lifecycle import BEFORE_SAVE, LifecycleModelMixin, hook
from model_utils.models import TimeStampedModel
from phone_field import PhoneField


class LocContact(models.Model):
    contact = models.CharField(
        "Name of the primary contact",
        max_length=100,
        blank=True,
        help_text="Full name of the primary contact.",
    )
    contact_email = models.EmailField(
        "Email address of the primary contact", blank=True
    )
    contact_phone = PhoneField("Work phone number for the location", blank=True)

    class Meta:
        abstract = True


class Gmaps(models.Model):
    address = map_fields.AddressField(max_length=200, blank=True)
    geolocation = map_fields.GeoLocationField(max_length=100, blank=True)

    class Meta:
        abstract = True


class Location(LifecycleModelMixin, TimeStampedModel, LocContact, Gmaps, models.Model):
    title = models.CharField(
        "Name of the location.",
        max_length=120,
        unique=True,
        help_text="Formal name for the location.",
    )
    slug = models.SlugField(
        verbose_name="Location address", unique=True, default="Auto-generated"
    )
    address1 = models.CharField("Street Address line 1", max_length=120, blank=True)
    address2 = models.CharField("Street Address line 1", max_length=120, blank=True)
    city = models.CharField("City", max_length=50, blank=True)
    state = models.CharField("State", max_length=2, default="Tx")
    zipcode = models.CharField("Zip code", max_length=5, blank=True)
    website = models.URLField(
        "Location Web site",
        blank=True,
        null=True,
        help_text="Optional web site of the location.",
    )

    def __str__(self):
        return f"{self.title} in {self.city}"

    @hook(BEFORE_SAVE, when="title", has_changed=True)
    def build_slug(self):
        newslug = slugify(self.title)
        if self.slug != newslug:
            self.slug = newslug

    def get_absolute_url(self):
        return reverse("locations.views.detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "location"
        verbose_name_plural = "locations"

taichi_dfw/resources/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django_lifecycle import BEFORE_SAVE, LifecycleModelMixin, hook
from model_utils.models import TimeStampedModel


class Resource(LifecycleModelMixin, TimeStampedModel):
    title = models.CharField(
        "Short title for resource",
        max_length=90,
        unique=True,
        null=False,
        help_text="Short title for each resource",
    )
    slug = models.SlugField(
        verbose_name="Resource address", unique=True, default="Auto-generated"
    )
    description = models.TextField(verbose_name="Description", blank=True)
    VISIBILITY_CHOICES = (
        ("public", "Show to public"),
        ("private", "Show to members only."),
    )
    visibility = models.CharField(
        max_length=8,
        choices=VISIBILITY_CHOICES,
        default="private",
        help_text="Control whether guests can see this resource.",
    )
    RESOURCE_TYPE = (
        ("website", "Website useful for this style or series."),
        ("book", "Link to page where the book can be purchased"),
        ("slideshow", "Slide show of photos or presentation"),
        ("video", "Link to video"),
        ("photo", "Link to single photo"),
        ("store", "Link to the store website"),
        ("tournament", "Link to tournament website"),
        ("none", "Resource does not have a link"),
    )
    link_type = models.CharField(
        max_length=20,
        choices=RESOURCE_TYPE,
        default="none",
        help_text="Classification of this link by type for sub-menus.",
    )
    link = models.URLField("Link address to be used under the description", blank=True)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )

    class Meta:
        verbose_name = "resource"
        verbose_name_plural = "resources"

    def get_absolute_url(self):
        return reverse("resources.views.detail", kwargs={"slug": self.slug})

    def __str__(self):
        return f"{self.link_type}:{self.title}"

    @hook(BEFORE_SAVE, when="title", has_changed=True)
    def build_slug(self):
        newslug = slugify(self.title)
        if self.slug != newslug:
            self.slug = newslug

taichi_dfw/users/models.py
import uuid
from pathlib import Path

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from phone_field import PhoneField

from taichi_dfw.resources.models import Resource
from taichi_dfw.styles.models import Style


def profile_pic_path(instance, filename):
    path = Path(filename)
    return f"profile_pics/{uuid.uuid4()}{path.suffix}"


class User(AbstractUser):
    """Default user for dfwtaichi."""

    #: First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    gmail = models.EmailField(
        "GMail address",
        blank=True,
        max_length=200,
        help_text="GMail address, used for authentication.",
    )
    phone = PhoneField("home phone.", blank=True)
    cell = PhoneField(
        "cell phone", blank=True, help_text="Number used for text notifications"
    )
    bio = models.TextField("TaiChi biography.", blank=True)
    biophoto = models.ImageField(upload_to=profile_pic_path, blank=True, default="")
    resources = models.ManyToManyField(to=Resource)
    favorite_style = models.ForeignKey(
        to=Style,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Select your default TaiChi Style.",
    )
    city = models.CharField(
        "City of residence.",
        max_length=30,
        help_text="Preferred city for TaiChi meetings.",
        blank=True,
        null=True,
    )
    leaderFlag = models.BooleanField("User is a leader", default=False)
    sponsor = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="User who applied leader designation.",
    )

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

taichi_dfw/styles/forms.py
# from dfwtaichi.users.models import User
# from django import forms
# from django.conf import settings

# from .models import Series

"""
class SeriesMembersChangeListForm(forms.ModelForm):
    members = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(), required=False
    )


class SeriesLeadersChangeListForm(forms.ModelForm):
    leaders = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(leaderFlag=True)
    )


class MembersAttendeesChangeListForm(forms.ModelForm):
    here = forms.ModelMultipleChoiceField(queryset=Series.objects.("members"))
"""

taichi_dfw/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

taichi_dfw/locations/views.py
# from django.shortcuts import render

# Create your views here.

taichi_dfw/resources/views.py
# from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import Resource


class ResourceListView(ListView):
    model = Resource


resource_list_view = ResourceListView.as_view()


class ResourceDetailView(DetailView):
    model = Resource


resource_detail_view = ResourceDetailView.as_view()

taichi_dfw/styles/views.py
# from django.shortcuts import render
# from json import dumps

from django.views.generic import DetailView, ListView

from .models import (  # SeriesResource, Style, StyleResource,; Members,
    Meeting,
    Series,
    Style,
)

# from taichi_dfw.locations.models import Location


class StyleListView(ListView):
    model = Style


style_list_view = StyleListView.as_view()


class ActiveSeriesMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sty = context["style"]
        context["resources"] = sty.styleResource.all()
        ser = sty.seriesStyle.all()
        context["series"] = ser
        return context


class StyleDetailView(ActiveSeriesMixin, DetailView):
    model = Style


style_detail_view = StyleDetailView.as_view()


class SeriesDetailView(DetailView):
    model = Series


series_detail_view = SeriesDetailView.as_view()


class MeetingSiteMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        meet = kwargs["object"]
        context["meetGeo"] = meet.location.geolocation
        context["meetTitle"] = meet.location.title
        return context


class MeetingDetailView(MeetingSiteMixin, DetailView):
    model = Meeting


meeting_detail_view = MeetingDetailView.as_view()

taichi_dfw/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        usr = context["user"]
        user_series = usr.membersSeries.all()
        context["seriesList"] = user_series
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = [
        "name",
        "city",
        "phone",
        "cell",
        "bio",
        "favorite_style",
        "gmail",
    ]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

taichi_dfw/templates/styles/meeting_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Meeting: {{ object.series.style.title }} : {{ object.series.title }}{% endblock %}

{% block content %}
<div class="container">
  <div class="">
    <h2>{{ object.series.title }}</h2>
    {% if object.location %}
      <p>{{ object.location.title }}</p>
      <div id="map"></div>
    {% endif %}
    {% if object.room %}
      <p>This meeting is in room {{ object.room }}</p>
    {% endif %}
    {% if object.day %}
      <p>Meeting at {{ object.start }} for {{ object.length }} minutes on {{ object.day }}</p>
    {% endif %}
    {% if object.leader %}
        <p>The meeting organizer or leader is {{ object.leader.member.name }}.
    {% endif %}
    {% if object.meetingAttendees %}
      <p>{{ object.meetingAttendees.count }}Members attended:</p>
      <ul>
        {% for mbr in object.meetingRoll %}
          <li>
            <span >{{ mbr.member.name}}</span>
            {% if  mbr.last_meeting %}
              <span>Last Meeting: {{ mbr.last_meeting }}</span>
            {% endif %}
          </li>
       {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>
<!-- End Action buttons -->

{% endblock content %}

{% block javascript %}
  {{ block.super }}
    <script>
    // Show the map on this page with markers
    function initMap() {
      // The location of DFW Metroplex
      const meetingSite = new google.maps.LatLng({{meetGeo.lat}},{{meetGeo.lon}});
      // The map, centered at Uluru
      const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 17,
        center: meetingSite,
      });
      // The marker, positioned at Uluru
      const marker = new google.maps.Marker({
        position: meetingSite,
        map: map,
        title: "{{ meetTitle }}",
      });
    }
  </script>
{% endblock javascript %}

taichi_dfw/templates/styles/series_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Series: {{ object.style.title }} : {{ object.title }}{% endblock %}

{% block content %}
<div class="container">
  <div class="">
    <h2>{{ object.title }}</h2>
    {% if object.description %}
      <p>{{ object.description }}</p>
    {% endif %}
    {% if object.visibilty %}
      <p>This series of classes or meetings is {{ object.visibilty }}</p>
    {% endif %}
    {% if object.membership %}
      <p>This series of classes or meetings is {{ object.membership }}</p>
      {% if object.membership == 'closed' %}
        <p>Contact one of the leaders listed below for permission to join.</p>
        {% endif %}
    {% endif %}
    {% if object.activeLeaders %}
      <p>Leaders or Instructors:</p>
      <ul>
        {% for ldr in object.activeLeaders %}
          <li class="row" >
            <a href=" {% url "users:detail" ldr.member.username %}" class="col-sm-3">{{ ldr.member.name}}</a>
            <span class="col-sm-3">{{ ldr.member.email}}</span>
            <span class="col-sm-6"> since {{ ldr.since}}</span>
          </li>
       {% endfor %}
      </ul>
    {% endif %}
    {% if object.activeMembers %}
      <p>Members:</p>
      <ul>
        {% for mbr in object.activeMembers %}
          <li>
            <a href=" {% url "users:detail" mbr.member.username %}" >{{ mbr.member.name}}</a>
            {% if  mbr.last_meeting %}
              <span>Last Meeting: {{ mbr.last_meeting }}</span>
            {% endif %}
          </li>
       {% endfor %}
      </ul>
    {% endif %}
    {% if object.futureMeetings %}
      <p>Upcoming meetings</p>
      <ul>
        {% for meet in object.futureMeetings %}
          <li>
            <a href=" {% url "styles:meeting-detail" meet.id %}" > {{ meet.location.title }} </a>
            {% if meet.room %}
            <span >In room {{ meet.room }}</span>
            {% endif %}
            <p>at {{ meet.start }} on {{ meet.day }}</p>
          </li>
        {% endfor %}
    {% endif %}
      </ul>

  </div>
</div>
<!-- End Action buttons -->

{% endblock content %}

taichi_dfw/templates/styles/style_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}style: {{ object.title }}{% endblock %}

{% block content %}
<div class="container">
  <div class="col-sm-12">
    <h2>{{ object.title }}</h2>
    {% if object.description %}
      <p>{{ object.description }}</p>
    {% endif %}
    {% if object.wikipedia %}
      <p>
        See the <a href="{{object.wikipedia}}" target="_blank" rel="noopener noreferrer">Reference Page </a>
      for more information.
      </p>
    {% endif %}
    {% if object.owner.email %}
      <p>Owner: {{ object.owner.name }} (Email:{{ object.owner.email }})</p>
    {% endif %}
     {% if series %}
      <p>Series:</p>
      <ul>
        {% for ser in series %}
          <li class="col-sm-9"><a href="{% url 'styles:series-detail' ser.slug %}" >
            {{ ser.title }}</a> with {{ ser.memberCount }} members.</li>

          {% if ser.activeLeaders %}
          <ul>
            {% for ldr in ser.activeLeaders %}
              <li class="col-sm-3">{{ ldr.member.name }}</li>
            {% endfor %}
          </ul>
          {% endif %}
       {% endfor %}
      </ul>
    {% endif %}
    {% if object.resources %}
      <p>Resources:</p>
      <ul>
        {% for res in object.resources.all %}
          <li>{{ res.link_type }}: <a href="{{ res.link }}" target="_blank" rel="noopener noreferrer">
            {{ res.title }}</a></li>
       {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>
<!-- End Action buttons -->

{% endblock content %}

taichi_dfw/templates/styles/style_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}List of Styles{% endblock %}

{% block content %}
  <h2>Styles List</h2>
<div class="container">
  <ul>
    {%  for style in style_list %}
      <li><a href="#TODO">{{ style.title }}</a></li>
    {% endfor %}
  </ul>
</div>
<!-- End Action buttons -->

{% endblock content %}